### ISSUE TITLE
diagrams doesn't install with ghc 8.8.1

### ISSUE THREAD

**Issue by GeorgeCo** [diagrams/diagrams#18]
diagrams doesn't install with ghc 8.8.1, with --allow-new I get:

[71 of 73] Compiling Diagrams.Backend.CmdLine ( src/Diagrams/Backend/CmdLine.hs, dist/build/Diagrams/Backend/CmdLine.o )

src/Diagrams/Backend/CmdLine.hs:314:56: error:
    • Could not deduce (MonadFail m) arising from a use of ‘hex’
      from the context: Monad m
        bound by the type signature for:
                   readHexColor :: forall (m :: * -> *).
                                   (Applicative m, Monad m) =>
                                   String -> m (AlphaColour Double)
        at src/Diagrams/Backend/CmdLine.hs:306:1-76
      Possible fix:
        add (MonadFail m) to the context of
          the type signature for:
            readHexColor :: forall (m :: * -> *).
                            (Applicative m, Monad m) =>
                            String -> m (AlphaColour Double)
    • In the second argument of ‘(<$>)’, namely ‘hex a b’
      In the first argument of ‘(<*>)’, namely ‘sRGB <$> hex a b’
      In the first argument of ‘(<*>)’, namely
        ‘sRGB <$> hex a b <*> hex c d’
    |
314 |         [a,b,c,d,e,f,g,h] -> withOpacity <$> (sRGB <$> hex a b <*> hex c d <*> hex e f) <*> hex g h
    |                                                        ^^^^^^^
cabal: Failed to build diagrams-lib-1.4.2.3 (which is required by
diagrams-1.4). See the build log above for details.

**Comment by byorgey** [comment]
Thanks for the report!  I am currently working on getting everything updated for GHC 8.8.  Hopefully this should be addressed in the next few days.

**Comment by sebeaumont** [comment]
Any news on a ghc-8.8 release? -- I would like to install diagrams as part of hyper-extra.

**Comment by byorgey** [comment]
I have continued to make slow but steady progress.  Though obviously my hope that it would be done "in the next few days" was ridiculously overoptimistic.  It's a bunch of work because the diagrams ecosystem has a lot of packages in it, and it's not a simple issue of bumping some upper bounds, there are nontrivial changes that have to be made to get everything working and compatible with GHC 8.8 and older versions at the same time.  I also don't have a ton of time to work on it (I'm not complaining, just explaining why it is taking a while).  Ideally we would figure out how to find some more people willing and able to help with maintenance.

**Comment by byorgey** [comment]
Just an update, the most frequently-used diagrams packages are all updated now.  If something still isn't working or there's another package you want that's not updated yet, feel free to nag!

**Comment by treeowl** [comment]
There still hasn't been a Hackage release since 2016. Maybe it's time?

**Comment by GeorgeCo** [comment]
cabal v1-install diagrams --allow-new works for me on ghc 8.10.1

**Comment by TrueBoxGuy** [comment]
> There still hasn't been a Hackage release since 2016. Maybe it's time?

Diagrams merely acts as a wrapper for the other diagrams library, so there's no need to rerelease it. The other libraries have been updated recently, but, as GeorgeCo said, allow newer on base is needed to get diagrams working with GHC 8.10.1.

**Comment by joseedil** [comment]
Can't compile on 8.10.1 under OSX. Relates to this GHC issue: https://gitlab.haskell.org/ghc/ghc/-/issues/18446.

```
[ 6 of 73] Compiling Diagrams.Parametric.Adjust ( src/Diagrams/Parametric/Adjust.hs, dist/build/Diagrams/Parametric/Adjust.o, dist/build/Diagrams/Parametric/Adjust.dyn_o )
<command line>: can't load framework: Cocoa (not found)
cabal: Failed to build diagrams-lib-1.4.3 (which is required by diagrams-1.4)
```

Under 8.10.4 which solves this problem, it fails in another point:

```
[71 of 73] Compiling Diagrams.Backend.CmdLine ( src/Diagrams/Backend/CmdLine.hs, dist/build/Diagrams/Backend/CmdLine.o, dist/build/Diagrams/Backend/CmdLine.dyn_o )

src/Diagrams/Backend/CmdLine.hs:223:23: error:
    • Couldn't match expected type ‘ParseError’
                  with actual type ‘Maybe String -> ParseError’
    • Probable cause: ‘ShowHelpText’ is applied to too few arguments
      In the first argument of ‘abortOption’, namely ‘ShowHelpText’
      In the expression: abortOption ShowHelpText
      In the expression:
        abortOption ShowHelpText
          $ mconcat [long "help", short '?', help "Show this help text"]
    |
223 | helper' = abortOption ShowHelpText $ mconcat
    |                       ^^^^^^^^^^^^
cabal: Failed to build diagrams-lib-1.4.3 (which is required by diagrams-1.4)
```

**Comment by byorgey** [comment]
The issue with 9.0.1 is known, and is addressed by https://github.com/diagrams/active/pull/36 (though not released yet).  As for the error with `ShowHelpText`, are you building with `--allow-newer`?  At first glance my guess is the error is due to a breaking change in `optparse-applicative`.  Maybe try adding `--constraint='optparse-applicative < 0.16'` ?

**Comment by joseedil** [comment]
Using this `cabal install diagrams --allow-new --constraint='optparse-applicative < 0.16'` seems to work on 8.10.4, thanks.

Any clue on why version 1.4 is not on the newest stackage packages?

**Comment by GeorgeCo** [comment]
Thanks Brent ! As you probably know it now also installs on 9.2.1

**Comment by byorgey** [comment]
Yes, I just got done updating most of the diagrams packages for GHC 9.2, and will hopefully stay more on top of updates from here on.  I've just been going through and trying to close any outdated issues.
